export enum UISectionKeysEnum {
    ADMIN_PROFILE = 'ADMIN_PROFILE',
    ADMIN_SERVICES = 'ADMIN_SERVICES',
    ADMIN_CALENDAR = 'ADMIN_CALENDAR',
    ADMIN_RESERVATIONS = 'ADMIN_RESERVATIONS',
    ADMIN_HOLIDAYS = 'ADMIN_HOLIDAYS',
}